const questionsData = [
  {
    id: 1,
    prompt: 'Am the life of the party.',
    isPositive: true,
    trait: 'extraversion',
    value: 3,
  },
  {
    id: 2,
    prompt: 'Feel little concern for others.',
    isPositive: false,
    trait: 'agreeableness',
    value: 3,
  },
  {
    id: 3,
    prompt: 'Am always prepared.',
    isPositive: true,
    trait: 'conscientiousness',
    value: 3,
  },
  {
    id: 4,
    prompt: 'Get stressed out easily.',
    isPositive: true,
    trait: 'neuroticism',
    value: 3,
  },
  {
    id: 5,
    prompt: 'Have a rich vocabulary.',
    isPositive: true,
    trait: 'openness',
    value: 3,
  },
  {
    id: 6,
    prompt: "Don't talk a lot.",
    isPositive: false,
    trait: 'extraversion',
    value: 3,
  },
  {
    id: 7,
    prompt: 'Am interested in people.',
    isPositive: true,
    trait: 'agreeableness',
    value: 3,
  },
  {
    id: 8,
    prompt: 'Leave my belongings around.',
    isPositive: false,
    trait: 'conscientiousness',
    value: 3,
  },
  {
    id: 9,
    prompt: 'Am relaxed most of the time.',
    isPositive: false,
    trait: 'neuroticism',
    value: 3,
  },
  {
    id: 10,
    prompt: 'Have difficulty understanding abstract ideas.',
    isPositive: false,
    trait: 'openness',
    value: 3,
  },
  {
    id: 11,
    prompt: 'Feel comfortable around people.',
    isPositive: true,
    trait: 'extraversion',
    value: 3,
  },
  {
    id: 12,
    prompt: 'Insult people.',
    isPositive: false,
    trait: 'agreeableness',
    value: 3,
  },
  {
    id: 13,
    prompt: 'Pay attention to details.',
    isPositive: true,
    trait: 'conscientiousness',
    value: 3,
  },
  {
    id: 14,
    prompt: 'Worry about things.',
    isPositive: true,
    trait: 'neuroticism',
    value: 3,
  },
  {
    id: 15,
    prompt: 'Have a vivid imagination.',
    isPositive: true,
    trait: 'openness',
    value: 3,
  },
  {
    id: 16,
    prompt: 'Keep in the background.',
    isPositive: false,
    trait: 'extraversion',
    value: 3,
  },
  {
    id: 17,
    prompt: "Sympathize with others' feelings.",
    isPositive: true,
    trait: 'agreeableness',
    value: 3,
  },
  {
    id: 18,
    prompt: 'Make a mess of things.',
    isPositive: false,
    trait: 'conscientiousness',
    value: 3,
  },
  {
    id: 19,
    prompt: 'Seldom feel blue.',
    isPositive: false,
    trait: 'neuroticism',
    value: 3,
  },
  {
    id: 20,
    prompt: 'Am not interested in abstract ideas.',
    isPositive: false,
    trait: 'openness',
    value: 3,
  },
  {
    id: 21,
    prompt: 'Start conversations.',
    isPositive: true,
    trait: 'extraversion',
    value: 3,
  },
  {
    id: 22,
    prompt: "Am not interested in other people's problems.",
    isPositive: false,
    trait: 'agreeableness',
    value: 3,
  },
  {
    id: 23,
    prompt: 'Get chores done right away.',
    isPositive: true,
    trait: 'conscientiousness',
    value: 3,
  },
  {
    id: 24,
    prompt: 'Am easily disturbed.',
    isPositive: true,
    trait: 'neuroticism',
    value: 3,
  },
  {
    id: 25,
    prompt: 'Have excellent ideas.',
    isPositive: true,
    trait: 'openness',
    value: 3,
  },
  {
    id: 26,
    prompt: 'Have little to say.',
    isPositive: false,
    trait: 'extraversion',
    value: 3,
  },
  {
    id: 27,
    prompt: 'Have a soft heart.',
    isPositive: true,
    trait: 'agreeableness',
    value: 3,
  },
  {
    id: 28,
    prompt: 'Often forget to put things back in their proper place.',
    isPositive: false,
    trait: 'conscientiousness',
    value: 3,
  },
  {
    id: 29,
    prompt: 'Get upset easily.',
    isPositive: true,
    trait: 'neuroticism',
    value: 3,
  },
  {
    id: 30,
    prompt: 'Do not have a good imagination.',
    isPositive: false,
    trait: 'openness',
    value: 3,
  },
  {
    id: 31,
    prompt: 'Talk to a lot of different people at parties.',
    isPositive: true,
    trait: 'extraversion',
    value: 3,
  },
  {
    id: 32,
    prompt: 'Am not really interested in others.',
    isPositive: false,
    trait: 'agreeableness',
    value: 3,
  },
  {
    id: 33,
    prompt: 'Like order.',
    isPositive: true,
    trait: 'conscientiousness',
    value: 3,
  },
  {
    id: 34,
    prompt: 'Change my mood a lot.',
    isPositive: true,
    trait: 'neuroticism',
    value: 3,
  },
  {
    id: 35,
    prompt: 'Am quick to understand things.',
    isPositive: true,
    trait: 'openness',
    value: 3,
  },
  {
    id: 36,
    prompt: "Don't like to draw attention to myself.",
    isPositive: false,
    trait: 'extraversion',
    value: 3,
  },
  {
    id: 37,
    prompt: 'Take time out for others.',
    isPositive: true,
    trait: 'agreeableness',
    value: 3,
  },
  {
    id: 38,
    prompt: 'Shirk my duties.',
    isPositive: false,
    trait: 'conscientiousness',
    value: 3,
  },
  {
    id: 39,
    prompt: 'Have frequent mood swings.',
    isPositive: true,
    trait: 'neuroticism',
    value: 3,
  },
  {
    id: 40,
    prompt: 'Use difficult words.',
    isPositive: true,
    trait: 'openness',
    value: 3,
  },
  {
    id: 41,
    prompt: "Don't mind being the center of attention.",
    isPositive: true,
    trait: 'extraversion',
    value: 3,
  },
  {
    id: 42,
    prompt: "Feel others' emotions.",
    isPositive: true,
    trait: 'agreeableness',
    value: 3,
  },
  {
    id: 43,
    prompt: 'Follow a schedule.',
    isPositive: true,
    trait: 'conscientiousness',
    value: 3,
  },
  {
    id: 44,
    prompt: 'Get irritated easily.',
    isPositive: true,
    trait: 'neuroticism',
    value: 3,
  },
  {
    id: 45,
    prompt: 'Spend time reflecting on things.',
    isPositive: true,
    trait: 'openness',
    value: 3,
  },
  {
    id: 46,
    prompt: 'Am quiet around strangers.',
    isPositive: false,
    trait: 'extraversion',
    value: 3,
  },
  {
    id: 47,
    prompt: 'Make people feel at ease.',
    isPositive: true,
    trait: 'agreeableness',
    value: 3,
  },
  {
    id: 48,
    prompt: 'Am exacting in my work.',
    isPositive: true,
    trait: 'conscientiousness',
    value: 3,
  },
  {
    id: 49,
    prompt: 'Often feel blue.',
    isPositive: true,
    trait: 'neuroticism',
    value: 3,
  },
  {
    id: 50,
    prompt: 'Am full of ideas.',
    isPositive: true,
    trait: 'openness',
    value: 3,
  },
];

export default questionsData;
